services:
  web:
    image: mazemaster420:latest
    build: .
    ports:
      - "5000-5002:5000"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: "50M"
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet: